version: 2

jobs:
  build:
    docker:
      - image: circleci/rust
    environment:
    steps:
      - checkout
      - run:
          name: build
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build --features=$CARGO_FEATURES
      - run:
          name: test
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo test --features=$CARGO_FEATURES
      - run:
          name: build --release
          command: |
            rustc --version
            cargo --version
            cargo build --release